[build]
    Command = "npm run lambda-build"
    functions= "functions"
    
[functions]
    directory = "functions"

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200